export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLES_FROM_DATE = 'FILTER_ARTICLES_FROM_DATE'

export const FILTER_ARTICLES_TO_DATE = 'FILTER_ARTICLES_TO_DATE'